[[redirects]]
  from = "https://unruffled-wing-c7f459.netlify.app/"
  to = "https://bobble.fun/"
  status = 301
  force = true
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}